apiVersion: v2
appVersion: "12.0"
version: 8.0.36
kubeVersion: ">=1.16.0-0"
name: odoo
description: All-in-one business software. Beautiful. Easy-to-use. CRM, Accounting, PM, HR, Procurement, Point of Sale, MRP, Marketing, etc.
type: application
home: https://truecharts.org/docs/charts/stable/odoo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/odoo.png
keywords:
  - odoo
  - crm
  - pm
  - hr
  - accounting
  - mrp
  - marketing
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/odoo
  - https://www.odoo.com/
  - https://hub.docker.com/repository/docker/ricardon85/odoo-nzl-trustcode
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.4.12
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 8.0.56
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
