image:
  repository: ricardon85/odoo-nzl-trustcode
  pullPolicy: IfNotPresent
  tag: 12.0@sha256:1cbf35e0dc8ca4b89a14b84a800906b5284061ea7a94a32db55315f1a24aa881

env:
  PG_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  PG_PORT: 5432
  PG_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  PG_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

service:
  main:
    ports:
      main:
        port: 8069
        targetPort: 8069
  odoo:
    enabled: true
    ports:
      xmlrpcs:
        enabled: true
        port: 8071
        targetPort: 8071
      longpolling:
        enabled: true
        port: 8072
        targetPort: 8072

persistence:
  odoo:
    enabled: true
    mountPath: "/var/lib/odoo"
  addons:
    enabled: true
    mountPath: "/mnt/extra-addons"

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: odoo
  postgresqlDatabase: postgres

portal:
  enabled: true
